name: build-msys2

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        msystem :
        - mingw64
        #- ucrt64
    name: Build OF for MSYS2 - ${{ matrix.msystem }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        release: false
        msystem: ${{ matrix.msystem }}
        install: >-
          git
          unzip
          rsync
          wget
        pacboy: >-
          assimp:p
          boost:p
          cairo:p
          ccache:p
          curl:p
          fd:p
          freeglut:p
          FreeImage:p
          glew:p
          glfw:p
          glm:p
          harfbuzz:p
          libsndfile:p
          libusb:p
          libxml2:p
          mpg123:p
          nlohmann-json:p
          ntldd:p
          openal:p
          opencv:p
          poco:p
          pugixml:p
          rtaudio:p
          toolchain:p
          uriparser:p
          utf8cpp:p
          zlib:p
    - name: Install dependencies
      run: ./scripts/ci/msys2/install.sh
    - name: Build
      run: ./scripts/ci/msys2/build.sh
    - name: Run tests
      run: ./scripts/ci/msys2/run_tests.sh
