name: build-msys2

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        cfg:
        - {flavor: mingw64, pkg-prefix: mingw-w64-x86_64}
        #- ucrt64
        #- clang64
        #- clangarm64
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: ${{ matrix.cfg.flavor }}
        install: >-
          git
          unzip
          rsync
          wget
        pacboy: >-
            ccache:p
    - name: Cache compile
      id: cache-compile
      uses: actions/cache@v3
      env:
        cache-name: cache-keep-compile
      with:
        path: libs/openFrameworksCompiled/lib/msys2/**/
        key: ${{ runner.os }}-${{matrix.cfg.flavor}}-${{ env.cache-name }}-${{ hashFiles('**/*.cpp') }}
        restore-keys: |
          ${{ runner.os }}-${{matrix.cfg.flavor}}-${{ env.cache-name }}-
    
    - name: Install dependencies
      run: ./scripts/ci/msys2/install.sh
      env:
        MSYSTEM: ${{ matrix.cfg.flavor }}
        MINGW_PACKAGE_PREFIX: ${{ matrix.cfg.pkg-prefix }}
    - name: Build
      run: ./scripts/ci/msys2/build.sh
      env:
        MSYSTEM: ${{ matrix.cfg.flavor }}
        MINGW_PACKAGE_PREFIX: ${{ matrix.cfg.pkg-prefix }}
    - name: Run tests
      run: ./scripts/ci/msys2/run_tests.sh
      env:
        MSYSTEM: ${{ matrix.cfg.flavor }}
        MINGW_PACKAGE_PREFIX: ${{ matrix.cfg.pkg-prefix }}
