name: build-msys2

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        msystem:
        - mingw64
        - ucrt64
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: ${{matrix.msystem}}
        install: >-
          make
          rsync
          unzip
        pacboy: >-
          assimp:p
          boost:p
          cairo:p
          curl:p
          freeglut:p
          FreeImage:p
          gcc:p
          glew:p
          glfw:p
          glm:p
          harfbuzz:p
          libsndfile:p
          libusb:p
          libxml2:p
          mpg123:p
          nlohmann-json:p
          ntldd:p
          openal:p
          opencv:p
          pkgconf:p
          poco:p
          pugixml:p
          rtaudio:p
          uriparser:p
          utf8cpp:p
          zlib:p
    - name: Cache compile
      id: cache-compile
      uses: actions/cache@v3
      env:
        cache-name: cache-keep-compile
      with:
        path: |
          libs/openFrameworksCompiled/lib/msys2/*.a
          libs/openFrameworksCompiled/lib/msys2/**/
          addons/obj/msys2/**/
          examples/templates/allAddonsExample/obj/**/
          examples/templates/emptyExample/obj/**/
        key: ${{ runner.os }}-${{matrix.msystem}}-${{ env.cache-name }}-${{ hashFiles('**/*.cpp') }}
        restore-keys: |
          ${{ runner.os }}-${{matrix.msystem}}-${{ env.cache-name }}-
    - name: Install dependencies
      run: ./scripts/msys2/download_libs.sh --silent
    - name: Build
      run: ./scripts/ci/msys2/build.sh
    - name: Run tests
      run: ./scripts/ci/msys2/run_tests.sh
