name: MSYS2 GHA
on: [push, pull_request]

jobs:
  msys2:
    build:
      runs-on: windows-latest
      strategy:
        matrix:
          system: [64,32]
      defaults:
        run:
          shell: msys2 {0}
      steps:
        env: 
            MSYSTEM: MINGW${{ matrix.system }}
        - uses: actions/checkout@v2
        - uses: msys2/setup-msys2@v2
          with:
            update: true
            install: >-
              git
              unzip
              rsync
              wget
        - name: Install dependencies
          run: |
            echo 'Installing dependencies!'
            ./scripts/ci/msys2/install.sh
        - name: Build
          run: |
            echo 'Building Of'
            ./scripts/ci/msys2/build.sh
        - name: Run Tests
          run: |
            echo 'Running Test'
            ./scripts/ci/msys2/run_tests.sh